/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as EditarPerfilRouteImport } from './routes/editar-perfil'
import { Route as ConversasRouteImport } from './routes/conversas'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CarteiraRouteImport } from './routes/carteira'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfiguracoesIndexRouteImport } from './routes/configuracoes.index'
import { Route as PerfilUsernameRouteImport } from './routes/perfil.$username'

const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const EditarPerfilRoute = EditarPerfilRouteImport.update({
  id: '/editar-perfil',
  path: '/editar-perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversasRoute = ConversasRouteImport.update({
  id: '/conversas',
  path: '/conversas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteiraRoute = CarteiraRouteImport.update({
  id: '/carteira',
  path: '/carteira',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesIndexRoute = ConfiguracoesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const PerfilUsernameRoute = PerfilUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => PerfilRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carteira': typeof CarteiraRoute
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/conversas': typeof ConversasRoute
  '/editar-perfil': typeof EditarPerfilRoute
  '/explorar': typeof ExplorarRoute
  '/notificacoes': typeof NotificacoesRoute
  '/perfil': typeof PerfilRouteWithChildren
  '/perfil/$username': typeof PerfilUsernameRoute
  '/configuracoes/': typeof ConfiguracoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carteira': typeof CarteiraRoute
  '/conversas': typeof ConversasRoute
  '/editar-perfil': typeof EditarPerfilRoute
  '/explorar': typeof ExplorarRoute
  '/notificacoes': typeof NotificacoesRoute
  '/perfil': typeof PerfilRouteWithChildren
  '/perfil/$username': typeof PerfilUsernameRoute
  '/configuracoes': typeof ConfiguracoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carteira': typeof CarteiraRoute
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/conversas': typeof ConversasRoute
  '/editar-perfil': typeof EditarPerfilRoute
  '/explorar': typeof ExplorarRoute
  '/notificacoes': typeof NotificacoesRoute
  '/perfil': typeof PerfilRouteWithChildren
  '/perfil/$username': typeof PerfilUsernameRoute
  '/configuracoes/': typeof ConfiguracoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carteira'
    | '/configuracoes'
    | '/conversas'
    | '/editar-perfil'
    | '/explorar'
    | '/notificacoes'
    | '/perfil'
    | '/perfil/$username'
    | '/configuracoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carteira'
    | '/conversas'
    | '/editar-perfil'
    | '/explorar'
    | '/notificacoes'
    | '/perfil'
    | '/perfil/$username'
    | '/configuracoes'
  id:
    | '__root__'
    | '/'
    | '/carteira'
    | '/configuracoes'
    | '/conversas'
    | '/editar-perfil'
    | '/explorar'
    | '/notificacoes'
    | '/perfil'
    | '/perfil/$username'
    | '/configuracoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarteiraRoute: typeof CarteiraRoute
  ConfiguracoesRoute: typeof ConfiguracoesRouteWithChildren
  ConversasRoute: typeof ConversasRoute
  EditarPerfilRoute: typeof EditarPerfilRoute
  ExplorarRoute: typeof ExplorarRoute
  NotificacoesRoute: typeof NotificacoesRoute
  PerfilRoute: typeof PerfilRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editar-perfil': {
      id: '/editar-perfil'
      path: '/editar-perfil'
      fullPath: '/editar-perfil'
      preLoaderRoute: typeof EditarPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversas': {
      id: '/conversas'
      path: '/conversas'
      fullPath: '/conversas'
      preLoaderRoute: typeof ConversasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carteira': {
      id: '/carteira'
      path: '/carteira'
      fullPath: '/carteira'
      preLoaderRoute: typeof CarteiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/': {
      id: '/configuracoes/'
      path: '/'
      fullPath: '/configuracoes/'
      preLoaderRoute: typeof ConfiguracoesIndexRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/perfil/$username': {
      id: '/perfil/$username'
      path: '/$username'
      fullPath: '/perfil/$username'
      preLoaderRoute: typeof PerfilUsernameRouteImport
      parentRoute: typeof PerfilRoute
    }
  }
}

interface ConfiguracoesRouteChildren {
  ConfiguracoesIndexRoute: typeof ConfiguracoesIndexRoute
}

const ConfiguracoesRouteChildren: ConfiguracoesRouteChildren = {
  ConfiguracoesIndexRoute: ConfiguracoesIndexRoute,
}

const ConfiguracoesRouteWithChildren = ConfiguracoesRoute._addFileChildren(
  ConfiguracoesRouteChildren,
)

interface PerfilRouteChildren {
  PerfilUsernameRoute: typeof PerfilUsernameRoute
}

const PerfilRouteChildren: PerfilRouteChildren = {
  PerfilUsernameRoute: PerfilUsernameRoute,
}

const PerfilRouteWithChildren =
  PerfilRoute._addFileChildren(PerfilRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarteiraRoute: CarteiraRoute,
  ConfiguracoesRoute: ConfiguracoesRouteWithChildren,
  ConversasRoute: ConversasRoute,
  EditarPerfilRoute: EditarPerfilRoute,
  ExplorarRoute: ExplorarRoute,
  NotificacoesRoute: NotificacoesRoute,
  PerfilRoute: PerfilRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
