/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfiguracoesIndexRouteImport } from './routes/configuracoes.index'
import { Route as PerfilUsernameRouteImport } from './routes/perfil.$username'
import { Route as ConfiguracoesSuporteRouteImport } from './routes/configuracoes.suporte'
import { Route as ConfiguracoesSobreRouteImport } from './routes/configuracoes.sobre'
import { Route as ConfiguracoesLegalRouteImport } from './routes/configuracoes.legal'
import { Route as AuthenticatedVerificacaoRouteImport } from './routes/_authenticated/verificacao'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedEditarPerfilRouteImport } from './routes/_authenticated/editar-perfil'
import { Route as AuthenticatedConversasRouteImport } from './routes/_authenticated/conversas'
import { Route as AuthenticatedCarteiraRouteImport } from './routes/_authenticated/carteira'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ConfiguracoesSuporteIndexRouteImport } from './routes/configuracoes.suporte.index'
import { Route as ConfiguracoesLegalIndexRouteImport } from './routes/configuracoes.legal.index'
import { Route as ConfiguracoesSuporteSlugRouteImport } from './routes/configuracoes.suporte.$slug'
import { Route as ConfiguracoesLegalSlugRouteImport } from './routes/configuracoes.legal.$slug'
import { Route as ApiPublicWebhooksPagarmeRouteImport } from './routes/api/public/webhooks/pagarme'

const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesIndexRoute = ConfiguracoesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const PerfilUsernameRoute = PerfilUsernameRouteImport.update({
  id: '/perfil/$username',
  path: '/perfil/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesSuporteRoute = ConfiguracoesSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const ConfiguracoesSobreRoute = ConfiguracoesSobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const ConfiguracoesLegalRoute = ConfiguracoesLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const AuthenticatedVerificacaoRoute =
  AuthenticatedVerificacaoRouteImport.update({
    id: '/verificacao',
    path: '/verificacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEditarPerfilRoute =
  AuthenticatedEditarPerfilRouteImport.update({
    id: '/editar-perfil',
    path: '/editar-perfil',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConversasRoute = AuthenticatedConversasRouteImport.update({
  id: '/conversas',
  path: '/conversas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCarteiraRoute = AuthenticatedCarteiraRouteImport.update({
  id: '/carteira',
  path: '/carteira',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ConfiguracoesSuporteIndexRoute =
  ConfiguracoesSuporteIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ConfiguracoesSuporteRoute,
  } as any)
const ConfiguracoesLegalIndexRoute = ConfiguracoesLegalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConfiguracoesLegalRoute,
} as any)
const ConfiguracoesSuporteSlugRoute =
  ConfiguracoesSuporteSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => ConfiguracoesSuporteRoute,
  } as any)
const ConfiguracoesLegalSlugRoute = ConfiguracoesLegalSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ConfiguracoesLegalRoute,
} as any)
const ApiPublicWebhooksPagarmeRoute =
  ApiPublicWebhooksPagarmeRouteImport.update({
    id: '/api/public/webhooks/pagarme',
    path: '/api/public/webhooks/pagarme',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/explorar': typeof ExplorarRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/carteira': typeof AuthenticatedCarteiraRoute
  '/conversas': typeof AuthenticatedConversasRoute
  '/editar-perfil': typeof AuthenticatedEditarPerfilRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/verificacao': typeof AuthenticatedVerificacaoRoute
  '/configuracoes/legal': typeof ConfiguracoesLegalRouteWithChildren
  '/configuracoes/sobre': typeof ConfiguracoesSobreRoute
  '/configuracoes/suporte': typeof ConfiguracoesSuporteRouteWithChildren
  '/perfil/$username': typeof PerfilUsernameRoute
  '/configuracoes/': typeof ConfiguracoesIndexRoute
  '/configuracoes/legal/$slug': typeof ConfiguracoesLegalSlugRoute
  '/configuracoes/suporte/$slug': typeof ConfiguracoesSuporteSlugRoute
  '/configuracoes/legal/': typeof ConfiguracoesLegalIndexRoute
  '/configuracoes/suporte/': typeof ConfiguracoesSuporteIndexRoute
  '/api/public/webhooks/pagarme': typeof ApiPublicWebhooksPagarmeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explorar': typeof ExplorarRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/carteira': typeof AuthenticatedCarteiraRoute
  '/conversas': typeof AuthenticatedConversasRoute
  '/editar-perfil': typeof AuthenticatedEditarPerfilRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/verificacao': typeof AuthenticatedVerificacaoRoute
  '/configuracoes/sobre': typeof ConfiguracoesSobreRoute
  '/perfil/$username': typeof PerfilUsernameRoute
  '/configuracoes': typeof ConfiguracoesIndexRoute
  '/configuracoes/legal/$slug': typeof ConfiguracoesLegalSlugRoute
  '/configuracoes/suporte/$slug': typeof ConfiguracoesSuporteSlugRoute
  '/configuracoes/legal': typeof ConfiguracoesLegalIndexRoute
  '/configuracoes/suporte': typeof ConfiguracoesSuporteIndexRoute
  '/api/public/webhooks/pagarme': typeof ApiPublicWebhooksPagarmeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/explorar': typeof ExplorarRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/carteira': typeof AuthenticatedCarteiraRoute
  '/_authenticated/conversas': typeof AuthenticatedConversasRoute
  '/_authenticated/editar-perfil': typeof AuthenticatedEditarPerfilRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/verificacao': typeof AuthenticatedVerificacaoRoute
  '/configuracoes/legal': typeof ConfiguracoesLegalRouteWithChildren
  '/configuracoes/sobre': typeof ConfiguracoesSobreRoute
  '/configuracoes/suporte': typeof ConfiguracoesSuporteRouteWithChildren
  '/perfil/$username': typeof PerfilUsernameRoute
  '/configuracoes/': typeof ConfiguracoesIndexRoute
  '/configuracoes/legal/$slug': typeof ConfiguracoesLegalSlugRoute
  '/configuracoes/suporte/$slug': typeof ConfiguracoesSuporteSlugRoute
  '/configuracoes/legal/': typeof ConfiguracoesLegalIndexRoute
  '/configuracoes/suporte/': typeof ConfiguracoesSuporteIndexRoute
  '/api/public/webhooks/pagarme': typeof ApiPublicWebhooksPagarmeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/configuracoes'
    | '/explorar'
    | '/admin'
    | '/carteira'
    | '/conversas'
    | '/editar-perfil'
    | '/notificacoes'
    | '/perfil'
    | '/verificacao'
    | '/configuracoes/legal'
    | '/configuracoes/sobre'
    | '/configuracoes/suporte'
    | '/perfil/$username'
    | '/configuracoes/'
    | '/configuracoes/legal/$slug'
    | '/configuracoes/suporte/$slug'
    | '/configuracoes/legal/'
    | '/configuracoes/suporte/'
    | '/api/public/webhooks/pagarme'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/explorar'
    | '/admin'
    | '/carteira'
    | '/conversas'
    | '/editar-perfil'
    | '/notificacoes'
    | '/perfil'
    | '/verificacao'
    | '/configuracoes/sobre'
    | '/perfil/$username'
    | '/configuracoes'
    | '/configuracoes/legal/$slug'
    | '/configuracoes/suporte/$slug'
    | '/configuracoes/legal'
    | '/configuracoes/suporte'
    | '/api/public/webhooks/pagarme'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/configuracoes'
    | '/explorar'
    | '/_authenticated/admin'
    | '/_authenticated/carteira'
    | '/_authenticated/conversas'
    | '/_authenticated/editar-perfil'
    | '/_authenticated/notificacoes'
    | '/_authenticated/perfil'
    | '/_authenticated/verificacao'
    | '/configuracoes/legal'
    | '/configuracoes/sobre'
    | '/configuracoes/suporte'
    | '/perfil/$username'
    | '/configuracoes/'
    | '/configuracoes/legal/$slug'
    | '/configuracoes/suporte/$slug'
    | '/configuracoes/legal/'
    | '/configuracoes/suporte/'
    | '/api/public/webhooks/pagarme'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConfiguracoesRoute: typeof ConfiguracoesRouteWithChildren
  ExplorarRoute: typeof ExplorarRoute
  PerfilUsernameRoute: typeof PerfilUsernameRoute
  ApiPublicWebhooksPagarmeRoute: typeof ApiPublicWebhooksPagarmeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/': {
      id: '/configuracoes/'
      path: '/'
      fullPath: '/configuracoes/'
      preLoaderRoute: typeof ConfiguracoesIndexRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/perfil/$username': {
      id: '/perfil/$username'
      path: '/perfil/$username'
      fullPath: '/perfil/$username'
      preLoaderRoute: typeof PerfilUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/suporte': {
      id: '/configuracoes/suporte'
      path: '/suporte'
      fullPath: '/configuracoes/suporte'
      preLoaderRoute: typeof ConfiguracoesSuporteRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/configuracoes/sobre': {
      id: '/configuracoes/sobre'
      path: '/sobre'
      fullPath: '/configuracoes/sobre'
      preLoaderRoute: typeof ConfiguracoesSobreRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/configuracoes/legal': {
      id: '/configuracoes/legal'
      path: '/legal'
      fullPath: '/configuracoes/legal'
      preLoaderRoute: typeof ConfiguracoesLegalRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/_authenticated/verificacao': {
      id: '/_authenticated/verificacao'
      path: '/verificacao'
      fullPath: '/verificacao'
      preLoaderRoute: typeof AuthenticatedVerificacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/editar-perfil': {
      id: '/_authenticated/editar-perfil'
      path: '/editar-perfil'
      fullPath: '/editar-perfil'
      preLoaderRoute: typeof AuthenticatedEditarPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conversas': {
      id: '/_authenticated/conversas'
      path: '/conversas'
      fullPath: '/conversas'
      preLoaderRoute: typeof AuthenticatedConversasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carteira': {
      id: '/_authenticated/carteira'
      path: '/carteira'
      fullPath: '/carteira'
      preLoaderRoute: typeof AuthenticatedCarteiraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/configuracoes/suporte/': {
      id: '/configuracoes/suporte/'
      path: '/'
      fullPath: '/configuracoes/suporte/'
      preLoaderRoute: typeof ConfiguracoesSuporteIndexRouteImport
      parentRoute: typeof ConfiguracoesSuporteRoute
    }
    '/configuracoes/legal/': {
      id: '/configuracoes/legal/'
      path: '/'
      fullPath: '/configuracoes/legal/'
      preLoaderRoute: typeof ConfiguracoesLegalIndexRouteImport
      parentRoute: typeof ConfiguracoesLegalRoute
    }
    '/configuracoes/suporte/$slug': {
      id: '/configuracoes/suporte/$slug'
      path: '/$slug'
      fullPath: '/configuracoes/suporte/$slug'
      preLoaderRoute: typeof ConfiguracoesSuporteSlugRouteImport
      parentRoute: typeof ConfiguracoesSuporteRoute
    }
    '/configuracoes/legal/$slug': {
      id: '/configuracoes/legal/$slug'
      path: '/$slug'
      fullPath: '/configuracoes/legal/$slug'
      preLoaderRoute: typeof ConfiguracoesLegalSlugRouteImport
      parentRoute: typeof ConfiguracoesLegalRoute
    }
    '/api/public/webhooks/pagarme': {
      id: '/api/public/webhooks/pagarme'
      path: '/api/public/webhooks/pagarme'
      fullPath: '/api/public/webhooks/pagarme'
      preLoaderRoute: typeof ApiPublicWebhooksPagarmeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCarteiraRoute: typeof AuthenticatedCarteiraRoute
  AuthenticatedConversasRoute: typeof AuthenticatedConversasRoute
  AuthenticatedEditarPerfilRoute: typeof AuthenticatedEditarPerfilRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedVerificacaoRoute: typeof AuthenticatedVerificacaoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCarteiraRoute: AuthenticatedCarteiraRoute,
  AuthenticatedConversasRoute: AuthenticatedConversasRoute,
  AuthenticatedEditarPerfilRoute: AuthenticatedEditarPerfilRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedVerificacaoRoute: AuthenticatedVerificacaoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ConfiguracoesLegalRouteChildren {
  ConfiguracoesLegalSlugRoute: typeof ConfiguracoesLegalSlugRoute
  ConfiguracoesLegalIndexRoute: typeof ConfiguracoesLegalIndexRoute
}

const ConfiguracoesLegalRouteChildren: ConfiguracoesLegalRouteChildren = {
  ConfiguracoesLegalSlugRoute: ConfiguracoesLegalSlugRoute,
  ConfiguracoesLegalIndexRoute: ConfiguracoesLegalIndexRoute,
}

const ConfiguracoesLegalRouteWithChildren =
  ConfiguracoesLegalRoute._addFileChildren(ConfiguracoesLegalRouteChildren)

interface ConfiguracoesSuporteRouteChildren {
  ConfiguracoesSuporteSlugRoute: typeof ConfiguracoesSuporteSlugRoute
  ConfiguracoesSuporteIndexRoute: typeof ConfiguracoesSuporteIndexRoute
}

const ConfiguracoesSuporteRouteChildren: ConfiguracoesSuporteRouteChildren = {
  ConfiguracoesSuporteSlugRoute: ConfiguracoesSuporteSlugRoute,
  ConfiguracoesSuporteIndexRoute: ConfiguracoesSuporteIndexRoute,
}

const ConfiguracoesSuporteRouteWithChildren =
  ConfiguracoesSuporteRoute._addFileChildren(ConfiguracoesSuporteRouteChildren)

interface ConfiguracoesRouteChildren {
  ConfiguracoesLegalRoute: typeof ConfiguracoesLegalRouteWithChildren
  ConfiguracoesSobreRoute: typeof ConfiguracoesSobreRoute
  ConfiguracoesSuporteRoute: typeof ConfiguracoesSuporteRouteWithChildren
  ConfiguracoesIndexRoute: typeof ConfiguracoesIndexRoute
}

const ConfiguracoesRouteChildren: ConfiguracoesRouteChildren = {
  ConfiguracoesLegalRoute: ConfiguracoesLegalRouteWithChildren,
  ConfiguracoesSobreRoute: ConfiguracoesSobreRoute,
  ConfiguracoesSuporteRoute: ConfiguracoesSuporteRouteWithChildren,
  ConfiguracoesIndexRoute: ConfiguracoesIndexRoute,
}

const ConfiguracoesRouteWithChildren = ConfiguracoesRoute._addFileChildren(
  ConfiguracoesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ConfiguracoesRoute: ConfiguracoesRouteWithChildren,
  ExplorarRoute: ExplorarRoute,
  PerfilUsernameRoute: PerfilUsernameRoute,
  ApiPublicWebhooksPagarmeRoute: ApiPublicWebhooksPagarmeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
